[package]
distribution = "2201.10.0"
org = "ballerinax"
name = "hubspot.crm.commerce.taxes"
version = "@toml.version@"
license = ["Apache-2.0"]
authors = ["Ballerina"]
keywords = ["hubspot", "crm", "commerce", "taxes"]
repository = "https://github.com/ballerina-platform/module-ballerinax-hubspot.crm.commerce.taxes"

[build-options]
observabilityIncluded = true

[platform.java17]
graalvmCompatible = true
